# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCommands < Formula
  desc ""
  homepage ""
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yurikrupnik/go-commands/releases/download/v0.0.8/go-commands_0.0.8_Darwin_x86_64.tar.gz"
      sha256 "4243c4a4a66e0a3e6015c7ea217037413d34ef1198c8e6f5e290f6f9e6b77409"

      def install
        bin.install "go-commands"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yurikrupnik/go-commands/releases/download/v0.0.8/go-commands_0.0.8_Darwin_arm64.tar.gz"
      sha256 "621230951d29cd88c903604a091605c8c02240062ea8744997b1e09e94c7c343"

      def install
        bin.install "go-commands"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yurikrupnik/go-commands/releases/download/v0.0.8/go-commands_0.0.8_Linux_arm64.tar.gz"
      sha256 "78b244420ed83ed35305ead767e940099dfba648c29d5b72bbf26024de4f12e2"

      def install
        bin.install "go-commands"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yurikrupnik/go-commands/releases/download/v0.0.8/go-commands_0.0.8_Linux_x86_64.tar.gz"
      sha256 "56227116637aceca5f64aa8d6b4995b8aff5828bcf7fef3cca8b15152c4ad5d7"

      def install
        bin.install "go-commands"
      end
    end
  end
end
