# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCommands < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yurikrupnik/go-commands/releases/download/v0.0.3/go-commands_0.0.3_Darwin_arm64.tar.gz"
      sha256 "94986d8fb4a3e2fece976e0e006e9258363be9b8887d58f1e704b6ef66a21031"

      def install
        bin.install "go-commands"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yurikrupnik/go-commands/releases/download/v0.0.3/go-commands_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "e293da97d9684f44db4c3468057f9afedf289bad6e55b441ea92d2dbce99e023"

      def install
        bin.install "go-commands"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yurikrupnik/go-commands/releases/download/v0.0.3/go-commands_0.0.3_Linux_arm64.tar.gz"
      sha256 "79ed1d4668378141b49a0785dc7e955ad7390a5a256f4d940c57d0471fa549db"

      def install
        bin.install "go-commands"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yurikrupnik/go-commands/releases/download/v0.0.3/go-commands_0.0.3_Linux_x86_64.tar.gz"
      sha256 "92ad9d1fc1a5b8f8b6d5966ce8c6ef7af6d2b39b8bcbe18966b5a190de7e1f01"

      def install
        bin.install "go-commands"
      end
    end
  end
end
