apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-commands
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: go-commands
              image: yurikrupnik/go-commands:v0.0.14
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - /go-commands
          restartPolicy: OnFailure

---
#apiVersion: batch/v1
#kind: CronJob
#metadata:
#  name: wrk
#spec:
#  schedule: "* * * * *"
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          containers:
#            - name: wrk
#              image: wrk
#              imagePullPolicy: IfNotPresent
#              command: ["wrk"]
#              args:
#                - "-t12"
#                - "-c400"
#                - "-d30s"
#          restartPolicy: OnFailure

#  - name: wrk
#      image: yurikrupnik/wrk-m1
#      command: [ 'wrk' ]
#      args: [ "-t12", "-c400", "-d30s", {{ include "my-nginx.fullname" . }}:{{ .Values.service.port }}/hello' ]