name: Tags CI

on:
  push:
    tags:
      - '*'
env:
  DOCKER_BUILDKIT: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
#        with:
#          go-version: '1.18.2'
      - run: go version
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          install-only: true
      - name: Show GoReleaser version
        run: goreleaser -v
#      - uses: actions/upload-artifact@v3
#        with:
#          name: build-artifacts
#          path: dist/

